export type EmojiEntry = { emoji: string; name: string };
export type EmojiCategory = { label: string; emojis: EmojiEntry[] };

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    label: "Smileys",
    emojis: [
      { emoji: "😀", name: "grinning face" },
      { emoji: "😃", name: "grinning face with big eyes" },
      { emoji: "😄", name: "grinning face with smiling eyes" },
      { emoji: "😁", name: "beaming face with smiling eyes" },
      { emoji: "😆", name: "grinning squinting face" },
      { emoji: "😅", name: "grinning face with sweat" },
      { emoji: "😂", name: "face with tears of joy" },
      { emoji: "🤣", name: "rolling on the floor laughing" },
      { emoji: "😊", name: "smiling face with smiling eyes" },
      { emoji: "😇", name: "smiling face with halo" },
      { emoji: "🙂", name: "slightly smiling face" },
      { emoji: "😉", name: "winking face" },
      { emoji: "😍", name: "smiling face with heart eyes" },
      { emoji: "🥰", name: "smiling face with hearts" },
      { emoji: "😘", name: "face blowing a kiss" },
      { emoji: "😋", name: "face savoring food" },
      { emoji: "😎", name: "smiling face with sunglasses" },
      { emoji: "🤩", name: "star struck" },
      { emoji: "🥳", name: "partying face" },
      { emoji: "😏", name: "smirking face" },
      { emoji: "😒", name: "unamused face" },
      { emoji: "😔", name: "pensive face" },
      { emoji: "😢", name: "crying face" },
      { emoji: "😭", name: "loudly crying face" },
      { emoji: "😤", name: "face with steam from nose" },
      { emoji: "😠", name: "angry face" },
      { emoji: "🤬", name: "face with symbols on mouth" },
      { emoji: "😱", name: "face screaming in fear" },
      { emoji: "😳", name: "flushed face" },
      { emoji: "🤔", name: "thinking face" },
      { emoji: "🙄", name: "face with rolling eyes" },
      { emoji: "😴", name: "sleeping face" },
      { emoji: "🤢", name: "nauseated face" },
      { emoji: "🤧", name: "sneezing face" },
      { emoji: "😷", name: "face with medical mask" },
    ],
  },
  {
    label: "Gestures",
    emojis: [
      { emoji: "👋", name: "waving hand" },
      { emoji: "🤚", name: "raised back of hand" },
      { emoji: "✋", name: "raised hand" },
      { emoji: "🖐️", name: "hand with fingers splayed" },
      { emoji: "👌", name: "ok hand" },
      { emoji: "✌️", name: "victory hand" },
      { emoji: "🤞", name: "crossed fingers" },
      { emoji: "🤙", name: "call me hand" },
      { emoji: "👈", name: "backhand index pointing left" },
      { emoji: "👉", name: "backhand index pointing right" },
      { emoji: "👆", name: "backhand index pointing up" },
      { emoji: "👇", name: "backhand index pointing down" },
      { emoji: "☝️", name: "index pointing up" },
      { emoji: "👍", name: "thumbs up" },
      { emoji: "👎", name: "thumbs down" },
      { emoji: "✊", name: "raised fist" },
      { emoji: "👊", name: "oncoming fist" },
      { emoji: "👏", name: "clapping hands" },
      { emoji: "🙌", name: "raising hands" },
      { emoji: "🤝", name: "handshake" },
      { emoji: "🙏", name: "folded hands" },
      { emoji: "💪", name: "flexed biceps" },
      { emoji: "🦾", name: "mechanical arm" },
      { emoji: "👀", name: "eyes" },
      { emoji: "👁️", name: "eye" },
      { emoji: "👅", name: "tongue" },
      { emoji: "💋", name: "kiss mark" },
    ],
  },
  {
    label: "Hearts & Symbols",
    emojis: [
      { emoji: "❤️", name: "red heart" },
      { emoji: "🧡", name: "orange heart" },
      { emoji: "💛", name: "yellow heart" },
      { emoji: "💚", name: "green heart" },
      { emoji: "💙", name: "blue heart" },
      { emoji: "💜", name: "purple heart" },
      { emoji: "🖤", name: "black heart" },
      { emoji: "🤍", name: "white heart" },
      { emoji: "💔", name: "broken heart" },
      { emoji: "💕", name: "two hearts" },
      { emoji: "💞", name: "revolving hearts" },
      { emoji: "💖", name: "sparkling heart" },
      { emoji: "💘", name: "heart with arrow" },
      { emoji: "💝", name: "heart with ribbon" },
      { emoji: "✨", name: "sparkles" },
      { emoji: "⭐", name: "star" },
      { emoji: "🌟", name: "glowing star" },
      { emoji: "💫", name: "dizzy" },
      { emoji: "🔥", name: "fire" },
      { emoji: "💧", name: "droplet" },
      { emoji: "💯", name: "hundred points" },
      { emoji: "✅", name: "check mark button" },
      { emoji: "❌", name: "cross mark" },
      { emoji: "⚠️", name: "warning" },
      { emoji: "🎉", name: "party popper" },
      { emoji: "🎊", name: "confetti ball" },
      { emoji: "🏆", name: "trophy" },
      { emoji: "🥇", name: "first place medal" },
    ],
  },
  {
    label: "Nature",
    emojis: [
      { emoji: "🐶", name: "dog face" },
      { emoji: "🐱", name: "cat face" },
      { emoji: "🐭", name: "mouse face" },
      { emoji: "🐹", name: "hamster" },
      { emoji: "🐰", name: "rabbit face" },
      { emoji: "🦊", name: "fox" },
      { emoji: "🐻", name: "bear" },
      { emoji: "🐼", name: "panda" },
      { emoji: "🐨", name: "koala" },
      { emoji: "🐯", name: "tiger face" },
      { emoji: "🦁", name: "lion" },
      { emoji: "🐸", name: "frog" },
      { emoji: "🐧", name: "penguin" },
      { emoji: "🐦", name: "bird" },
      { emoji: "🦋", name: "butterfly" },
      { emoji: "🌸", name: "cherry blossom" },
      { emoji: "🌺", name: "hibiscus" },
      { emoji: "🌻", name: "sunflower" },
      { emoji: "🌹", name: "rose" },
      { emoji: "🌿", name: "herb" },
      { emoji: "🍀", name: "four leaf clover" },
      { emoji: "🌲", name: "evergreen tree" },
      { emoji: "🌴", name: "palm tree" },
      { emoji: "🌊", name: "water wave" },
      { emoji: "🌈", name: "rainbow" },
      { emoji: "☀️", name: "sun" },
      { emoji: "🌙", name: "crescent moon" },
      { emoji: "❄️", name: "snowflake" },
      { emoji: "⚡", name: "lightning" },
      { emoji: "🌪️", name: "tornado" },
    ],
  },
  {
    label: "Food",
    emojis: [
      { emoji: "🍎", name: "red apple" },
      { emoji: "🍊", name: "tangerine" },
      { emoji: "🍋", name: "lemon" },
      { emoji: "🍇", name: "grapes" },
      { emoji: "🍓", name: "strawberry" },
      { emoji: "🍒", name: "cherries" },
      { emoji: "🍑", name: "peach" },
      { emoji: "🥭", name: "mango" },
      { emoji: "🍍", name: "pineapple" },
      { emoji: "🥥", name: "coconut" },
      { emoji: "🥝", name: "kiwi fruit" },
      { emoji: "🍅", name: "tomato" },
      { emoji: "🥑", name: "avocado" },
      { emoji: "🌽", name: "ear of corn" },
      { emoji: "🍕", name: "pizza" },
      { emoji: "🍔", name: "hamburger" },
      { emoji: "🌮", name: "taco" },
      { emoji: "🍜", name: "steaming bowl" },
      { emoji: "🍣", name: "sushi" },
      { emoji: "🍩", name: "doughnut" },
      { emoji: "🎂", name: "birthday cake" },
      { emoji: "🍰", name: "shortcake" },
      { emoji: "🍦", name: "soft ice cream" },
      { emoji: "🍫", name: "chocolate bar" },
      { emoji: "☕", name: "hot beverage" },
      { emoji: "🧃", name: "beverage box" },
      { emoji: "🍺", name: "beer mug" },
      { emoji: "🥂", name: "clinking glasses" },
    ],
  },
  {
    label: "Objects & Travel",
    emojis: [
      { emoji: "📱", name: "mobile phone" },
      { emoji: "💻", name: "laptop" },
      { emoji: "🖥️", name: "desktop computer" },
      { emoji: "⌨️", name: "keyboard" },
      { emoji: "📷", name: "camera" },
      { emoji: "📺", name: "television" },
      { emoji: "🎮", name: "video game" },
      { emoji: "🎸", name: "guitar" },
      { emoji: "🎹", name: "musical keyboard" },
      { emoji: "📚", name: "books" },
      { emoji: "📝", name: "memo" },
      { emoji: "✏️", name: "pencil" },
      { emoji: "🔍", name: "magnifying glass tilted left" },
      { emoji: "💡", name: "light bulb" },
      { emoji: "🔑", name: "key" },
      { emoji: "🔒", name: "locked" },
      { emoji: "⚙️", name: "gear" },
      { emoji: "🔧", name: "wrench" },
      { emoji: "🏠", name: "house" },
      { emoji: "🏢", name: "office building" },
      { emoji: "✈️", name: "airplane" },
      { emoji: "🚀", name: "rocket" },
      { emoji: "🚗", name: "automobile" },
      { emoji: "🚲", name: "bicycle" },
      { emoji: "⛵", name: "sailboat" },
      { emoji: "🗺️", name: "world map" },
      { emoji: "🏔️", name: "snow capped mountain" },
      { emoji: "🏖️", name: "beach with umbrella" },
    ],
  },
];
